### PR TITLE
feat: add workflow for continuous delivery

### PR DESCRIPTION
**Pull request by yogyagamage**
- Fixes #https://github.com/INRIA/spoon/issues/5302

The added workflow is based on https://github.com/INRIA/spoon/actions/workflows/jreleaser.yml.

### CODE REVIEW

**Comment by MartinWitt** [comment]
Hey, have you add the github secrets? Will review the rest tomorrow.

**Comment by yogyagamage** [comment]
> Hey, have you add the github secrets? 

Yes, I have added them. 

> Will review the rest tomorrow.

Thanks

**Comment by monperrus** [comment]
thanks @yogyagamage let's now see how it works by updating spoon-core

**Comment by monperrus** [comment]
Requires a bit of adjustement, see https://github.com/SpoonLabs/spoon-maven-plugin/actions/runs/6056685311/job/16437012477#step:11:28

**Pull request merged**
