### PR TITLE
Fix error when no sources in multimodule

### PR DESCRIPTION
**Pull request by surli**
This PR intends to fix https://github.com/INRIA/spoon/issues/1901 

⚠️ This PR changes the behaviour of Spoon Maven Plugin: now when a error comes from a missing source directory or a wrong classpath, a warning is triggered and the project is ignored.

### CODE REVIEW

**Comment by tmortagne** [comment]
> warning This PR changes the behaviour of Spoon Maven Plugin: now when a error comes from a missing source directory or a wrong classpath, a warning is triggered and the project is ignored.

I guess it would not hurt to make this behavior configurable if you really need to fail :)

**Comment by monperrus** [comment]
ok for me, I will merge it.

@tmortagne I would disagree with you: adding a configuration option always has a price in testing, documentation, ease of understanding for newcomers and maintenance.

**Comment by tmortagne** [comment]
My point was more about the warning itself and the fact that maybe some people count on the old behavior (which probably already have test, etc.).

**Comment by surli** [comment]
> My point was more about the warning itself and the fact that maybe some people count on the old behavior (which probably already have test, etc.).

I don't expect that people were counting on this behaviour. And anyway as it breaks a behaviour I will certainly release it as spoon-maven-plugin:3.0.

**Comment by monperrus** [comment]
thanks @surli

**Pull request merged**
