### PR TITLE
review Add option to use generated sources

### PR DESCRIPTION
**Pull request by surli**
Fix https://github.com/INRIA/spoon/issues/1902

### CODE REVIEW

**Comment by surli** [comment]
@tmortagne I have several issues making my test passing with antlr. But the core concept of what you want is there: would it bother you to check the version of the plugin provided in my branch https://github.com/surli/spoon-maven-plugin/tree/add-option-use-generated-sources against xwiki-rendering-wikimodel? 

```bash
cd /tmp
git clone https://github.com/surli/spoon-maven-plugin.git
cd spoon-maven-plugin
git checkout add-option-use-generated-sources
mvn install -DskipTests
```

Then edit your pom.xml of xwiki-rendering-wikimodel to change the version of spoon-maven-plugin to `2.9-SNAPSHOT` and add the following configuration on the plugin:

```xml
<configuration>
   <withGeneratedSources>true</withGeneratedSources>
</configuration>
```

Just to check if I'm in the right direction...

**Comment by tmortagne** [comment]
Works like a charm. I also tested with what is produced by maven-jaxb2-plugin (xwiki-commons-repository-model) and it's fine too.

The logged inputs are right too:

> Inputs: /media/data/projets/xwiki/src/git/xwiki-rendering/xwiki-rendering-wikimodel/src/main/java:/media/data/projets/xwiki/src/git/xwiki-rendering/xwiki-rendering-wikimodel/target/generated-sources/javacc

> Inputs: /media/data/projets/xwiki/src/git/xwiki-commons/xwiki-commons-core/xwiki-commons-repository/xwiki-commons-repository-model/src/main/java:/media/data/projets/xwiki/src/git/xwiki-commons/xwiki-commons-core/xwiki-commons-repository/xwiki-commons-repository-model/target/generated-sources/xjc

I also confirm that if I have a forbidden method in a non generated source it's properly catched.

Looks like you are on the right track :)

**Comment by tmortagne** [comment]
One small comment: I feel withGeneratedSources should be enabled by default since it's using standard Maven inputs and automatically disabled if srcFolders is provided instead of the current behavior.

**Comment by surli** [comment]
>  I feel withGeneratedSources should be enabled by default since it's using standard Maven inputs

I wasn't quite sure about that, but then I saw that we actually clear the current value of `compileSourceRoots` if the user don't specify to use `isCompileOriginalSources`: then it totally makes sense to also use the generated sources by default. 👍 

> and automatically disabled if srcFolders/srcFolder is provided instead of the current behavior.

It's already the case: srcFolder(s) option has always the priority.

@monperrus so for me the PR is ready, note that I did not manage to create a proper unit test but we do have a test-project that we could use to test the new feature in test directory.

**Comment by monperrus** [comment]
thanks a lot!

**Pull request merged**
