### PR TITLE
Change the version number of Maven to 3.3.9

### PR DESCRIPTION
**Pull request by surli**

### CODE REVIEW

**Comment by surli** [comment]
@tmortagne for you this change is enough?

**Comment by tmortagne** [comment]
I did not tested it but it should be yes since that's the version XWiki build agents use and the version all XWiki Maven plugins depends on.

**Comment by surli** [comment]
@monperrus ok to merge it?

**Comment by monperrus** [comment]
Thanks!

**Comment by surli** [comment]
@tmortagne before I do a new release, would it be possible for you to check that the plugin is now working?

**Comment by tmortagne** [comment]
I just tested the 2.8-SNAPSHOT but I can't build the parent pom which define the execution of the spoon plugin.

I get 

```
[ERROR] Failed to execute goal fr.inria.gforge.spoon:spoon-maven-plugin:2.8-SNAPSHOT:check (default) on project xwiki-commons-pom: No source directory for XWiki Commons - Root POM project. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal fr.inria.gforge.spoon:spoon-maven-plugin:2.8-SNAPSHOT:check (default) on project xwiki-commons-pom: No source directory for XWiki Commons - Root POM project.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: No source directory for XWiki Commons - Root POM project.
    at fr.inria.gforge.spoon.SpoonMojoGenerate.execute (SpoonMojoGenerate.java:212)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.lang.RuntimeException: No source directory for XWiki Commons - Root POM project.
    at fr.inria.gforge.spoon.configuration.AbstractSpoonConfigurationBuilder.addInputFolder (AbstractSpoonConfigurationBuilder.java:66)
    at fr.inria.gforge.spoon.SpoonMojoGenerate.buildArguments (SpoonMojoGenerate.java:158)
    at fr.inria.gforge.spoon.SpoonMojoGenerate.initMojo (SpoonMojoGenerate.java:192)
    at fr.inria.gforge.spoon.SpoonMojoGenerate.execute (SpoonMojoGenerate.java:206)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
```

The plugin should be bulletproof regarding non Java or empty source modules IMO (like it used to be actually).

**Comment by surli** [comment]
Hmm thanks for your feedback, I'll fix that one. But we're ok that you don't have a version problem anymore?

**Comment by tmortagne** [comment]
I can't say. I would need to build the parent pom first.

**Comment by surli** [comment]
@tmortagne could you try again now it should be fixed?

**Comment by tmortagne** [comment]
I still get the following when building the parent pom:

```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal fr.inria.gforge.spoon:spoon-maven-plugin:2.8-SNAPSHOT:check (default) on project xwiki-commons-pom: No source directory for XWiki Commons - Root POM project.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: No source directory for XWiki Commons - Root POM project.
    at fr.inria.gforge.spoon.SpoonMojoGenerate.execute (SpoonMojoGenerate.java:212)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.lang.RuntimeException: No source directory for XWiki Commons - Root POM project.
    at fr.inria.gforge.spoon.configuration.AbstractSpoonConfigurationBuilder.addInputFolder (AbstractSpoonConfigurationBuilder.java:66)
    at fr.inria.gforge.spoon.SpoonMojoGenerate.buildArguments (SpoonMojoGenerate.java:158)
    at fr.inria.gforge.spoon.SpoonMojoGenerate.initMojo (SpoonMojoGenerate.java:192)
    at fr.inria.gforge.spoon.SpoonMojoGenerate.execute (SpoonMojoGenerate.java:206)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
```

**Comment by surli** [comment]
> I create the following branch to reproduce the issue xwiki/xwiki-commons@feature-updatespoon 

Thanks, it will be easier indeed :)

**Comment by tmortagne** [comment]
Also to make sure I'm not doing something wrong :)

**Comment by surli** [comment]
Actually I did mvn clean install from the parent xwiki-commons to got the missing dependencies (custom enforcer, stuff like that) and then mvn clean install from xwiki-commons-pom and everything's fine for me. Are you sure you compile first the last snapshot of spoon-maven-plugin?

**Comment by tmortagne** [comment]
Forget that I was pulling my fork, so the parent builds fine.

Now I just noticed that soon-core 6.1.0 itself has a dependency on Maven 3.5.0 so it might create some issues.

**Comment by tmortagne** [comment]
Apart from this I tried to build a jar module and there is something very weird, it's like the spoon plugin was disabling /src/main/java/ as a source. I get the following log when building with `mvn clean install`:

    [INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ xwiki-commons-blame-api ---
    [INFO] Nothing to compile - all classes are up to date

then it try to build test (and obviously fail since none of the main classes has been built).

**Comment by surli** [comment]
Did you try with the last snapshot version of the Spoon plugin? I just checked it and obtained this: 

> [INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ xwiki-commons-blame-api ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 6 source files to /Users/urli/Github/xwiki-commons/xwiki-commons-core/xwiki-commons-blame/xwiki-commons-blame-api/target/classes

**Comment by tmortagne** [comment]
Well parent pom built well this time so I guess I have the latest version.

**Comment by tmortagne** [comment]
Here is what I did:
* in `spoon-maven-plugin`
** `git pull https://github.com/SpoonLabs/spoon-maven-plugin.git`
** `mvn clean install`
* in `xwiki-commons-pom/`
** `mvn clean install`
** in `xwiki-commons-blame/xwiki-commons-blame-api/`
** `mvn clean install`

I get the following build log when building (with Maven 3.3.9 but same with 3.5.0):

```
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building XWiki Commons - Blame - API 10.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ xwiki-commons-blame-api ---
[INFO] Deleting /media/data/projets/xwiki/src/git/xwiki-commons/xwiki-commons-core/xwiki-commons-blame/xwiki-commons-blame-api/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-plugins) @ xwiki-commons-blame-api ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-jcl-log4j-isolation) @ xwiki-commons-blame-api ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-glasshfish-jaxb) @ xwiki-commons-blame-api ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-commons-lang3) @ xwiki-commons-blame-api ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-commons-configuration2) @ xwiki-commons-blame-api ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-bouncycastle-ids) @ xwiki-commons-blame-api ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-javase-dependencies) @ xwiki-commons-blame-api ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-upper-bounds) @ xwiki-commons-blame-api ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-no-legacy-dependencies) @ xwiki-commons-blame-api ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-valid-poms) @ xwiki-commons-blame-api ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-platform-rendering-isolation) @ xwiki-commons-blame-api ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (check-dependency-version) @ xwiki-commons-blame-api ---
[INFO] 
[INFO] --- spoon-maven-plugin:2.8-SNAPSHOT:check (default) @ xwiki-commons-blame-api ---
2018-01-08 15:12:43,232 INFO spoon.Launcher - Spoon version 6.1.0
2018-01-08 15:12:43,233 INFO spoon.Launcher - running Spoon...
2018-01-08 15:12:43,233 INFO spoon.Launcher - start processing...
2018-01-08 15:12:43,966 INFO spoon.Launcher - org.xwiki.tool.spoon.ForbiddenInvocationProcessor
2018-01-08 15:12:44,109 INFO spoon.Launcher - end of processing: 
2018-01-08 15:12:44,110 INFO spoon.Launcher - no errors, no warnings
[INFO] 
[INFO] --- maven-remote-resources-plugin:1.5:process (xwiki-license-resources) @ xwiki-commons-blame-api ---
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ xwiki-commons-blame-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ xwiki-commons-blame-api ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-bundle-plugin:2.5.3:manifest (bundle-manifest) @ xwiki-commons-blame-api ---
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ xwiki-commons-blame-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /media/data/projets/xwiki/src/git/xwiki-commons/xwiki-commons-core/xwiki-commons-blame/xwiki-commons-blame-api/src/test/resources
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ xwiki-commons-blame-api ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /media/data/projets/xwiki/src/git/xwiki-commons/xwiki-commons-core/xwiki-commons-blame/xwiki-commons-blame-api/target/test-classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /media/data/projets/xwiki/src/git/xwiki-commons/xwiki-commons-core/xwiki-commons-blame/xwiki-commons-blame-api/src/test/java/org/xwiki/blame/internal/DefaultBlameManagerTest.java:[30,23] cannot find symbol
  symbol:   class AnnotatedContent
  location: package org.xwiki.blame
[ERROR] /media/data/projets/xwiki/src/git/xwiki-commons/xwiki-commons-core/xwiki-commons-blame/xwiki-commons-blame-api/src/test/java/org/xwiki/blame/internal/DefaultBlameManagerTest.java:[31,23] cannot find symbol
  symbol:   class AnnotatedElement
  location: package org.xwiki.blame
[ERROR] /media/data/projets/xwiki/src/git/xwiki-commons/xwiki-commons-core/xwiki-commons-blame/xwiki-commons-blame-api/src/test/java/org/xwiki/blame/internal/DefaultBlameManagerTest.java:[32,23] cannot find symbol
  symbol:   class BlameManager
  location: package org.xwiki.blame
[ERROR] /media/data/projets/xwiki/src/git/xwiki-commons/xwiki-commons-core/xwiki-commons-blame/xwiki-commons-blame-api/src/test/java/org/xwiki/blame/internal/DefaultBlameManagerTest.java:[59,46] cannot find symbol
  symbol:   class BlameManager
  location: class org.xwiki.blame.internal.DefaultBlameManagerTest
[ERROR] /media/data/projets/xwiki/src/git/xwiki-commons/xwiki-commons-core/xwiki-commons-blame/xwiki-commons-blame-api/src/test/java/org/xwiki/blame/internal/DefaultBlameManagerTest.java:[62,5] cannot find symbol
  symbol:   class BlameManager
  location: class org.xwiki.blame.internal.DefaultBlameManagerTest
[ERROR] /media/data/projets/xwiki/src/git/xwiki-commons/xwiki-commons-core/xwiki-commons-blame/xwiki-commons-blame-api/src/test/java/org/xwiki/blame/internal/DefaultBlameManagerTest.java:[59,101] cannot find symbol
  symbol:   class BlameManager
  location: class org.xwiki.blame.internal.DefaultBlameManagerTest
[ERROR] /media/data/projets/xwiki/src/git/xwiki-commons/xwiki-commons-core/xwiki-commons-blame/xwiki-commons-blame-api/src/test/java/org/xwiki/blame/internal/DefaultBlameManagerTest.java:[60,9] cannot find symbol
  symbol:   class DefaultBlameManager
  location: class org.xwiki.blame.internal.DefaultBlameManagerTest
[ERROR] /media/data/projets/xwiki/src/git/xwiki-commons/xwiki-commons-core/xwiki-commons-blame/xwiki-commons-blame-api/src/test/java/org/xwiki/blame/internal/DefaultBlameManagerTest.java:[85,9] cannot find symbol
  symbol:   class AnnotatedContent
  location: class org.xwiki.blame.internal.DefaultBlameManagerTest
[ERROR] /media/data/projets/xwiki/src/git/xwiki-commons/xwiki-commons-core/xwiki-commons-blame/xwiki-commons-blame-api/src/test/java/org/xwiki/blame/internal/DefaultBlameManagerTest.java:[118,18] cannot find symbol
  symbol:   class AnnotatedElement
  location: class org.xwiki.blame.internal.DefaultBlameManagerTest
[ERROR] /media/data/projets/xwiki/src/git/xwiki-commons/xwiki-commons-core/xwiki-commons-blame/xwiki-commons-blame-api/src/test/java/org/xwiki/blame/internal/DefaultBlameManagerTest.java:[121,9] cannot find symbol
  symbol:   class AnnotatedElement
  location: class org.xwiki.blame.internal.DefaultBlameManagerTest
[INFO] 10 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.754 s
[INFO] Finished at: 2018-01-08T15:12:45+01:00
[INFO] Final Memory: 43M/815M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:testCompile (default-testCompile) on project xwiki-commons-blame-api: Compilation failure: Compilation failure:
[ERROR] /media/data/projets/xwiki/src/git/xwiki-commons/xwiki-commons-core/xwiki-commons-blame/xwiki-commons-blame-api/src/test/java/org/xwiki/blame/internal/DefaultBlameManagerTest.java:[30,23] cannot find symbol
[ERROR] symbol:   class AnnotatedContent
[ERROR] location: package org.xwiki.blame
[ERROR] /media/data/projets/xwiki/src/git/xwiki-commons/xwiki-commons-core/xwiki-commons-blame/xwiki-commons-blame-api/src/test/java/org/xwiki/blame/internal/DefaultBlameManagerTest.java:[31,23] cannot find symbol
[ERROR] symbol:   class AnnotatedElement
[ERROR] location: package org.xwiki.blame
[ERROR] /media/data/projets/xwiki/src/git/xwiki-commons/xwiki-commons-core/xwiki-commons-blame/xwiki-commons-blame-api/src/test/java/org/xwiki/blame/internal/DefaultBlameManagerTest.java:[32,23] cannot find symbol
[ERROR] symbol:   class BlameManager
[ERROR] location: package org.xwiki.blame
[ERROR] /media/data/projets/xwiki/src/git/xwiki-commons/xwiki-commons-core/xwiki-commons-blame/xwiki-commons-blame-api/src/test/java/org/xwiki/blame/internal/DefaultBlameManagerTest.java:[59,46] cannot find symbol
[ERROR] symbol:   class BlameManager
[ERROR] location: class org.xwiki.blame.internal.DefaultBlameManagerTest
[ERROR] /media/data/projets/xwiki/src/git/xwiki-commons/xwiki-commons-core/xwiki-commons-blame/xwiki-commons-blame-api/src/test/java/org/xwiki/blame/internal/DefaultBlameManagerTest.java:[62,5] cannot find symbol
[ERROR] symbol:   class BlameManager
[ERROR] location: class org.xwiki.blame.internal.DefaultBlameManagerTest
[ERROR] /media/data/projets/xwiki/src/git/xwiki-commons/xwiki-commons-core/xwiki-commons-blame/xwiki-commons-blame-api/src/test/java/org/xwiki/blame/internal/DefaultBlameManagerTest.java:[59,101] cannot find symbol
[ERROR] symbol:   class BlameManager
[ERROR] location: class org.xwiki.blame.internal.DefaultBlameManagerTest
[ERROR] /media/data/projets/xwiki/src/git/xwiki-commons/xwiki-commons-core/xwiki-commons-blame/xwiki-commons-blame-api/src/test/java/org/xwiki/blame/internal/DefaultBlameManagerTest.java:[60,9] cannot find symbol
[ERROR] symbol:   class DefaultBlameManager
[ERROR] location: class org.xwiki.blame.internal.DefaultBlameManagerTest
[ERROR] /media/data/projets/xwiki/src/git/xwiki-commons/xwiki-commons-core/xwiki-commons-blame/xwiki-commons-blame-api/src/test/java/org/xwiki/blame/internal/DefaultBlameManagerTest.java:[85,9] cannot find symbol
[ERROR] symbol:   class AnnotatedContent
[ERROR] location: class org.xwiki.blame.internal.DefaultBlameManagerTest
[ERROR] /media/data/projets/xwiki/src/git/xwiki-commons/xwiki-commons-core/xwiki-commons-blame/xwiki-commons-blame-api/src/test/java/org/xwiki/blame/internal/DefaultBlameManagerTest.java:[118,18] cannot find symbol
[ERROR] symbol:   class AnnotatedElement
[ERROR] location: class org.xwiki.blame.internal.DefaultBlameManagerTest
[ERROR] /media/data/projets/xwiki/src/git/xwiki-commons/xwiki-commons-core/xwiki-commons-blame/xwiki-commons-blame-api/src/test/java/org/xwiki/blame/internal/DefaultBlameManagerTest.java:[121,9] cannot find symbol
[ERROR] symbol:   class AnnotatedElement
[ERROR] location: class org.xwiki.blame.internal.DefaultBlameManagerTest
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by surli** [comment]
I just follow your protocol with Maven 3.5.2 and JDK 8 without any error. I'll try with Maven 3.3.9 to see if I get an error.

**Comment by tmortagne** [comment]
I get the same with 3.5.2.

**Comment by surli** [comment]
That's weird then: I just checked on a fresh machine to be sure about my versions of Spoon and stuff and still no error here. Could you try to run "mvn dependency:purge-local-repository" on spoon-maven-plugin before trying back? Sorry to bother you on this one but it's hard to fix if I cannot replicate :-/

**Comment by tmortagne** [comment]
Still the same issue.

To be sure I cloned again the spoon plugin repository, used `mvn dependency:purge-local-repository` and built the plugin again but maven-compiler-plugin still can't find any source when I build `xwiki-commons-core/xwiki-commons-blame/xwiki-commons-blame-api`.

**Comment by tmortagne** [comment]
I updated the branch https://github.com/xwiki/xwiki-commons/tree/feature-updatespoon, could to pull it and try again to be sure we have the same thing.

**Comment by surli** [comment]
Hi @tmortagne 
I just tried with the branch, and I got the following error when launching mvn install from the root of the repo:

> INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-upper-bounds) @ xwiki-commons-tool-spoon ---
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for org.apache.maven:maven-model:3.3.9 paths to dependency are:
+-org.xwiki.commons:xwiki-commons-tool-spoon:10.0-SNAPSHOT
  +-fr.inria.gforge.spoon:spoon-core:6.1.0
    +-org.apache.maven:maven-model:3.3.9 (managed) <-- org.apache.maven:maven-model:3.5.0

**Comment by tmortagne** [comment]
Yes this is because spoon-core 6.1.0 depends on Maven 3.5.0 which is not the recommended version defined in the root pom (3.3.9).

**Comment by surli** [comment]
Hmmm I finally got the same message than you. I'll investigate later.

**Comment by tmortagne** [comment]
OK bad news (but good one for my mental health :slightly_smiling_face: ).

**Pull request merged**
