### PR TITLE
feature: simplify CI

### PR DESCRIPTION
**Pull request by MartinWitt**
I want to upgrade the CI to use all testprojects and have 3 stages. Additional adding a new testproject should be simplified. This is heavy wip, because i believe i need multiple tries to reach a good useable state. 

## The "new" CI Setup
I want to change the ci settings removing some ugly things and allow easier development.
As there are some major changes currently you cant test enough. A good CI makes life way easier. 

### The old CI Problems
It worked but had some issues:

1.The old CI needed sudo and some xml edit tools for changing the version. Looked terrible and had some issues. 
2. Adding a new project to the CI needed copy paste for all the commands. Adding a new project should be one line
3. Enforcing the current version was nearly impossible. In best case we hoped maven chooses the correct wrong.
4. Not all projects were part of the CI

### The new CI
We split the CI in 2 stages, unit test and real world project tests.
In the first stage we do a simple mvn install running all unit tests.
In the second stage, we have a list of jobs.
Each job is a test project like "custom-configuration" and runs the following script.
We don't run unit tests in stage 2 because here we assume they are correct. If not we skip stage 2.
``` YAML
  - "cd src/test/projects/processors"
  - "mvn install -DskipTests -Dmaven.compiler.source=1.8 -Dmaven.compiler.target=1.8"
  - "cd ../../../.."
  - "mvn install -DskipTests -Dmaven.compiler.source=1.8 -Dmaven.compiler.target=1.8"
  - "cd src/test/projects/"
  - "cd $projectName"
  - "mvn versions:use-latest-releases"
  - mvn package -"DspoonPlugin.version"=$pluginversion
  - "mvn clean"
  - "cd ../../../.."
```
#### How does this solve all the said issues?

1. The sudo command and xml edit is replaced by maven flags. We only relay on maven doing its job and no external dependency. `$pluginversion` is a environment variable having the value set in the job list, currently 3.5-SNAPSHOT.
2. The new CI only needs a new job added to the matrix. Adding the following line with FolderName replaced by the new project does the job. Sadly the 3.5-SNAPSHOT is needed in every line.
` - projectName="FolderName" pluginversion=3.5-SNAPSHOT`
3. As already written in 1. we let maven do this for us.
A testprojects need a property where we replace the version with the newest. 
```xml
  <properties>
    <spoonPlugin.version>3.4.1</spoonPlugin.version>
  </properties>
```
Open point here is, should we write a invalide version and let the CI fail if the replacement has issues? We could write e.g.  `<spoonPlugin.version>-1</spoonPlugin.version>`
4. All projects are now part of the CI. For this i added in every test project, the spoon plugin to the execution. 

#### new benefits
- We could test the plugin with jdk8 and jdk14(newest) without much hassle. 
- We run all test projects isolated in docker environments. 

#### Risk
- The CI takes "longer" and maybe some test projects are not really needed. But I don't think you can test too much.
- Adding new tests, that don't work with maven only is more difficult. 
- Every new major release needs to update all versions [here] (https://github.com/SpoonLabs/spoon-maven-plugin/pull/71/files#diff-354f30a63fb0907d4ad57269548329e3R4-R17)to the new snapshot e.g. 3.6-SNAPSHOT

wdyt?

### CODE REVIEW

**Comment by monperrus** [comment]
Thanks for the heavy-duty work (in progress).

**Comment by MartinWitt** [comment]
Added text about why I want to refactor the CI, benefits and risks .

**Comment by monperrus** [comment]
FYI  conflict here

**Comment by MartinWitt** [comment]
Fixed the conflict

**Comment by monperrus** [comment]
LGTM, ready for merge?

**Comment by MartinWitt** [comment]
yes

**Pull request merged**
